name: Stage 0 Validation (files only)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure required files exist
        run: |
          test -f README.md
          test -f index.html

      - name: Check required phrases in index.html
        run: |
          grep -q "Welcome to DevOps Stage 0" index.html
          grep -qi "Successfully deployed on" index.html
          grep -qi "Deployed:" index.html

      - name: Check README has name/slack/description
        run: |
          grep -qi "^\*\*Name:\*\*" README.md
          grep -qi "^\*\*Slack:\*\*" README.md
          grep -qi "^\*\*Description:\*\*" README.md

      # Optional: after deployment you can uncomment to require IP/domain in README
      # - name: (Optional) Require server URL in README (http://<ip>/ or http://domain/)
      #   run: |
      #     grep -Eqi 'http://([0-9]{1,3}\.){3}[0-9]{1,3}/|http://[A-Za-z0-9.-]+/?' README.md
